name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build CI Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile.ci
        push: false
        load: true
        tags: cube23-ci:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run build and tests in container
      run: ./test.sh

    - name: Upload screenshots artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: |
          screenshot_vk.png
          screenshot_opengl.png
        if-no-files-found: error
        retention-days: 1
